import type { NextPage } from "next";
import Head from "next/head";
import Artists from "../components/artists";
import Creators from "../components/creators";
import SplashImage from "../components/splash-image";

const Home: NextPage = () => {
  return (
    <div className="h-full">
      <Head>
        <title>Swee Lee Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SplashImage />
      <Creators />
      <Artists />
    </div>
  );
};

export default Home;
